apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
  labels:
    app: cartservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice

    spec:
      containers:
        - name: cartservice
          image: timnuwa/cartservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: cartservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: cartservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cartservice-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: cartservice-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8085"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cartservice-secrets
                  key: mysql-root-password
