apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-deployment
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice

    spec:
      containers:
        - name: paymentservice
          image: timnuwa/paymentservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: someKey1
            - name: CC_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: ccService
            - name: CC_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: ccServicePort
            - name: BANK_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: bankService
            - name: BANK_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: bankServicePort
            - name: PP_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: ppService
            - name: PP_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: paymentservice-config
                  key: ppServicePort
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: paymentservice-secrets
                  key: service-api-key
            