apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankservice-deployment
  labels:
    app: bankservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankservice
  template:
    metadata:
      labels:
        app: bankservice

    spec:
      containers:
        - name: bankservice
          image: timnuwa/bankservice:latest
          ports:
            - containerPort: 8096
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: bankservice-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: bankservice-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: bankservice-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: bankservice-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8085"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bankservice-secrets
                  key: mysql-root-password
