apiVersion: apps/v1
kind: Deployment
metadata:
  name: StatelessServiceB-deployment
  labels:
    app: StatelessServiceB
spec:
  replicas: 3
  selector:
    matchLabels:
      app: StatelessServiceB
  template:
    metadata:
      labels:
        app: StatelessServiceB

    spec:
      containers:
        - name: StatelessServiceB
          image: timnuwa/StatelessServiceB:latest
          ports:
            - containerPort: 8080
          env:
            - name: KEY1
              valueFrom:
                configMapKeyRef:
                  name: StatelessServiceB-config
                  key: someKey1
            - name: NEXT_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: StatelessServiceB-config
                  key: nextService
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: StatelessServiceB-secrets
                  key: service-api-key
            #MYSQL
            - name: MYSQL_HOST
              value: StatelessServiceB-db

            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "8085"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: StatelessServiceB-secrets
                  key: mysql-root-password